"""四種 README 模板：library / portfolio / course / saas。

每種模板是章節順序與文案語氣的差異，真正內容由 generator.py 填入。
"""
from __future__ import annotations

TEMPLATES = {
    "library": {
        "label": {"zh": "開源函式庫", "en": "Open-source library"},
        "sections": [
            "header", "badges", "intro", "features", "demo",
            "install", "usage", "api", "config",
            "project_structure", "test", "contributing",
            "license", "acknowledgement",
        ],
    },
    "portfolio": {
        "label": {"zh": "接案作品集", "en": "Portfolio piece"},
        "sections": [
            "header", "badges", "intro", "demo",
            "features", "tech_stack", "project_structure",
            "install", "usage", "highlights",
            "contact", "license",
        ],
    },
    "course": {
        "label": {"zh": "課程作業 / 專題", "en": "Course project"},
        "sections": [
            "header", "badges", "intro", "demo",
            "features", "tech_stack", "install", "usage",
            "project_structure", "members", "license", "reference",
        ],
    },
    "saas": {
        "label": {"zh": "商業產品 (SaaS)", "en": "Commercial SaaS"},
        "sections": [
            "header", "badges", "intro", "features", "demo",
            "tech_stack", "install", "usage", "config",
            "deployment", "pricing", "contact",
            "license",
        ],
    },
}

# 各語系的固定文案
STRINGS = {
    "zh": {
        "features": "## ✨ 功能特色",
        "demo": "## 🖼 展示",
        "install": "## 📦 安裝",
        "usage": "## 🚀 快速開始",
        "api": "## 📚 API 說明",
        "config": "## ⚙️ 設定",
        "tech_stack": "## 🛠 技術棧",
        "project_structure": "## 📁 專案結構",
        "test": "## ✅ 測試",
        "contributing": "## 🤝 貢獻指南",
        "license": "## 📄 授權",
        "acknowledgement": "## 🙏 致謝",
        "highlights": "## 💡 專案亮點（給業主看）",
        "contact": "## 📬 聯絡 / 接案資訊",
        "members": "## 👥 組員與分工",
        "reference": "## 📖 參考資料",
        "deployment": "## ☁️ 部署",
        "pricing": "## 💰 方案與商業模式",
        "toc": "## 📖 目錄",
        "prereq": "### 前置需求",
        "steps": "### 安裝步驟",
        "no_demo": "> （提示：把截圖放進 `images/` 或 `screenshots/` 資料夾，重新執行產生器就會自動嵌入。）",
        "todo_features": "- [ ] TODO：請補上核心功能（產生器已依專案結構預填，請自行潤飾）",
        "generated_footer": "\n---\n*本 README 由 [readme-generator](https://example.com) 自動產生，可再手動潤飾。*",
    },
    "en": {
        "features": "## ✨ Features",
        "demo": "## 🖼 Demo",
        "install": "## 📦 Installation",
        "usage": "## 🚀 Quick Start",
        "api": "## 📚 API",
        "config": "## ⚙️ Configuration",
        "tech_stack": "## 🛠 Tech Stack",
        "project_structure": "## 📁 Project Structure",
        "test": "## ✅ Testing",
        "contributing": "## 🤝 Contributing",
        "license": "## 📄 License",
        "acknowledgement": "## 🙏 Acknowledgements",
        "highlights": "## 💡 Highlights (for clients)",
        "contact": "## 📬 Contact / Hire Me",
        "members": "## 👥 Team & Roles",
        "reference": "## 📖 References",
        "deployment": "## ☁️ Deployment",
        "pricing": "## 💰 Pricing & Business Model",
        "toc": "## 📖 Table of Contents",
        "prereq": "### Prerequisites",
        "steps": "### Steps",
        "no_demo": "> (Tip: drop screenshots into `images/` or `screenshots/`, then re-run the generator to embed them.)",
        "todo_features": "- [ ] TODO: describe core features (pre-filled from project scan, please polish)",
        "generated_footer": "\n---\n*This README was generated by [readme-generator](https://example.com) — feel free to polish it further.*",
    },
}


def get_sections(template: str) -> list[str]:
    return TEMPLATES.get(template, TEMPLATES["library"])["sections"]


def valid_templates() -> list[str]:
    return list(TEMPLATES.keys())
